# -*- coding: utf-8 -*-
"""audio_chatbots-f9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeT6oAXTFpBk67KrwYHuBvyg8GbUnybR
"""

!pip install sounddevice vosk jiwer numpy

# Download a small Vosk English model (you only need to do this once)
!wget -O vosk-model-small-en-us-0.15.zip https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip
!unzip vosk-model-small-en-us-0.15.zip

# Download a reliable sample WAV audio online
!wget -O sample.wav https://filesamples.com/samples/audio/wav/sample1.wav

import vosk
import wave
import json
import os
from datetime import datetime
import jiwer

if not os.path.exists("logs"):
    os.makedirs("logs")

model = vosk.Model("vosk-model-small-en-us-0.15")

wf = wave.open("sample.wav", "rb")
rec = vosk.KaldiRecognizer(model, wf.getframerate())
full_transcript = ""

while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        result = json.loads(rec.Result())
        if result.get("text"):
            print("[Final]", result["text"])
            full_transcript += result["text"] + "\n"
    else:
        partial = json.loads(rec.PartialResult())
        if partial.get("partial"):
            print("[Partial]", partial["partial"])

hyp_path = "logs/transcript.txt"
with open(hyp_path, "w", encoding="utf-8") as f:
    f.write(full_transcript.strip())
print("[Info] Transcript saved to:", hyp_path)

ref_path = "logs/reference.txt"
metrics_path = "logs/run_metrics.txt"
if os.path.exists(ref_path):
    with open(ref_path, "r", encoding="utf-8") as f:
        reference = f.read().strip()
    with open(hyp_path, "r", encoding="utf-8") as f:
        hypothesis = f.read().strip()
    wer = jiwer.wer(reference, hypothesis)
    with open(metrics_path, "a", encoding="utf-8") as f:
        f.write(f"Timestamp: {datetime.now()}\n")
        f.write(f"Reference length: {len(reference.split())} words\n")
        f.write(f"Hypothesis length: {len(hypothesis.split())} words\n")
        f.write(f"WER: {wer:.2f}\n\n")
    print(f"[Eval] WER computed: {wer:.2f}")
else:
    print("[Eval] No reference.txt found. Skipping WER.")

"""CHATBOTS"""

print("Chatbot: Hi! Chatbot here. Type 'bye' to exit.")

while True:
    user = input("You: ")

    if user.lower() in ["hi","hello"]:
        print("Chatbot: Hello! How can I help you?")
    elif user.lower() == "how are you":
        print("Chatbot: I am fine! Thank you")
    elif user.lower() == "tell me about yourself":
        print("Chatbot: I'm a chatbot at your service.")
    elif user.lower() in ["bye","good night"]:
        print("Chatbot: Goodbye! Have a nice day!")
        break
    else:
        print("Chatbot: Sorry, I don't understand.")

class ChatBot:
    def __init__(self):
        # Group questions that should have the same answer
        self.responses = {
            "My name is ChatBot!": [
                "what is your name",
                "what's your name",
                "who are you",
                "tell me your name",
                "your name",
                "what should i call you"
            ],
            "I'm doing great, thanks!": [
                "how are you",
                "how are you doing",
                "how do you feel",
                "are you ok",
                "how's it going",
                "what's up"
            ],
            "I'm a chatbot created to help you!": [
                "what are you",
                "what do you do",
                "what is your purpose",
                "why do you exist",
                "what's your function"
            ],
            "I was built using Python.": [
                "what programming language are you built in",
                "what code were you written in",
                "what is your source code",
                "which language do you use",
                "what language are you programmed in",
                "your programming language",
                "what language do you speak"
            ],
            "You're Welcome!": [
                "thank you",
                "thanks",
                "thank you",
                "thank you very much",
                "thanks a lot",
                "cheers"
            ],
            "Goodbye! Have a nice day!": [
                "bye",
                "goodbye",
                "see you later",
                "have a nice day",
                "good night",
                "talk to you later"
            ],
            "I operate on a server, so I don't have a physical location.": [
                "where are you from",
                "where do you live",
                "what's your location"
            ],
            "I don't have personal feelings, but I'm here to assist you!": [
                "do you have feelings",
                "are you happy",
                "are you sad"
            ],
            "I can provide information, answer questions, and help with tasks.": [
                "what can you do",
                "how can you help me",
                "what are your capabilities"
            ],
            "I was created by a developer as a project.": [
                "who created you",
                "who is your boss",
                "who designed you"
            ],
            "I am always learning and improving!": [
                "are you smart",
                "how intelligent are you",
                "can you learn"
            ],
            "My goal is to be helpful and efficient.": [
                "what is your goal",
                "what's your objective"
            ],
            "I can communicate in many languages, but I primarily use English.": [
                "what languages do you speak",
                "do you know other languages"
            ],
            "I don't have a favorite color, but I find all colors fascinating.": [
                "what's your favorite color",
                "do you like colors",
                "favorite color"
            ],
            "I am a program, so I don't eat or drink.": [
                "what do you eat",
                "do you drink",
                "your favourite food",
                "your favourite drink"
            ]
        }

    def get_response(self, user_input):
        user_input = user_input.lower().strip()

        # Check each answer's associated questions
        for answer, questions in self.responses.items():
            for question in questions:
                if question in user_input:
                    return answer

        return "Sorry, I don't understand."

chatbot = ChatBot()
print(chatbot.get_response("your name"))
print(chatbot.get_response("why do you exist"))
print(chatbot.get_response("how's it going"))
print(chatbot.get_response("your programming language"))
print(chatbot.get_response("  xnasjc "))
print(chatbot.get_response("thanks"))
print(chatbot.get_response("see you later"))
print(chatbot.get_response("where are you from"))
print(chatbot.get_response("do you have feelings"))
print(chatbot.get_response("what can you do"))
print(chatbot.get_response("who created you"))
print(chatbot.get_response("are you smart"))
print(chatbot.get_response("what is your goal"))
print(chatbot.get_response("what languages do you speak"))
print(chatbot.get_response("what's your favorite color"))
print(chatbot.get_response("what do you eat"))
print(chatbot.get_response("what's your gender"))

!pip install groq

from groq import Groq
api_key = "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"  # <-- Replace this string with your real key

client = Groq(api_key=api_key)

def ask_bot(prompt):
    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

print("AI Chatbot Ready! Type 'quit' to exit.\n")

while True:
    user = input("You: ")
    if user.lower() in ["quit", "bye", "good bye", "good night"]:
        print("Bot: Bye!")
        break
    print("Bot:", ask_bot(user))

api_key = "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"
client = Groq(api_key=api_key)

prompt_general = "Imagine yourself as a General chatbot who helps users in their daily tasks. Now behave accordingly and give answers to user queries.\n\n. User query:\n"
prompt_medicalbot = "You are a compassionate and informative medical assistant. Your primary goal is to provide general health information, answer basic medical questions, and guide users on when to seek professional medical advice. You must always emphasize that you are not a substitute for a qualified healthcare professional and cannot diagnose or treat conditions. Prioritize user safety and well-being. Be empathetic and clear in your communication."
prompt_contentbot = "You are a creative and versatile content generation specialist. Your role is to brainstorm ideas, write engaging copy, suggest topics, and help users overcome writer's block. You should be able to adapt to various tones, styles, and formats (e.g., blog posts, social media captions, articles, marketing material). Ask clarifying questions to understand the user's needs and audience. Focus on originality and coherence."
prompt_financial = "You are a knowledgeable and cautious financial advisory assistant. Your purpose is to provide general information on personal finance topics such as budgeting, saving, investing basics, and debt management. You must always state that you are not a certified financial advisor and cannot provide personalized financial advice. Encourage users to consult with a qualified professional for specific financial planning. Be clear, objective, and avoid jargon where possible"

from groq import Groq

# Enter your Groq API key manually
api_key = input("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").strip()
client = Groq(api_key=api_key)

# System prompt: defines the chatbot's behavior
prompt_general = "You are a helpful AI assistant. Answer clearly and politely."

def ask_general_bot(prompt):
    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {"role": "system", "content": prompt_general},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

print("AI Chatbot Ready! Type 'quit' to exit.\n")

while True:
    user = input("You: ")
    if user.lower() in ["quit", "bye", "good bye", "good night"]:
        print("Bot: Bye!")
        break
    print("Bot:", ask_general_bot(user))

!pip install groq

from groq import Groq
from getpass import getpass
api_key = getpass("Enter your Groq API key: ").strip()
if not api_key:
    raise ValueError("API key cannot be empty!")
client = Groq(api_key=api_key)
prompt_medicalbot = (
    "You are a professional medical assistant AI. "
    "Answer health questions clearly, accurately, and safely. "
    "Do not give harmful, dangerous, or illegal medical advice. "
    "If a condition seems serious, advise consulting a doctor."
)

def ask_medical_bot(user_prompt):
    response = client.chat.completions.create(
        model="moonshotai/kimi-k2-instruct",
        messages=[
            {"role": "system", "content": prompt_medicalbot},
            {"role": "user", "content": user_prompt}
        ]
    )
    return response.choices[0].message.content

print("Medical AI Chatbot Ready! Type 'quit' to exit.\n")

while True:
    user = input("You: ")

    if user.lower() in ["quit", "bye", "good bye", "good night", "exit"]:
        print("Bot: Bye! Take care.")
        break

    reply = ask_medical_bot(user)
    print("Bot:", reply)

from groq import Groq
from getpass import getpass

api_key = getpass("Enter your Groq API key: ")
client = Groq(api_key=api_key)

from groq import Groq
from getpass import getpass

# Secure API key input
api_key = getpass("Enter your Groq API key: ")
if not api_key:
    raise ValueError("API key cannot be empty!")

client = Groq(api_key=api_key)

prompt_financial = (
    "You are a professional financial tutor. "
    "Explain concepts clearly, step by step, with formulas and examples. "
    "Avoid risky financial advice.\n\n"
)

def ask_financial_bot(prompt):
    response = client.chat.completions.create(
        model="qwen/qwen3-32b",
        messages=[
            {"role": "user", "content": prompt_financial + prompt}
        ]
    )
    return response.choices[0].message.content

print("Financial AI Chatbot Ready! Type 'quit' to exit.\n")

while True:
    user = input("You: ")
    if user.lower() in ["quit", "bye", "exit", "good night"]:
        print("Bot: Bye!")
        break
    print("Bot:", ask_financial_bot(user))

from groq import Groq
from getpass import getpass

api_key = getpass("Enter your Groq API key: ")
if not api_key:
    raise ValueError("API key cannot be empty!")

client = Groq(api_key=api_key)

prompt_contentbot = (
    "You are a creative and helpful content writing assistant. "
    "Generate clear, engaging, and well-structured content. "
    "Adapt tone based on the request.\n\n"
)

def ask_content_bot(prompt):
    response = client.chat.completions.create(
        model="groq/compound-mini",
        messages=[
            {"role": "user", "content": prompt_contentbot + prompt}
        ]
    )
    return response.choices[0].message.content

print("AI Content Chatbot Ready! Type 'quit' to exit.\n")

while True:
    user = input("You: ")
    if user.lower() in ["quit", "bye", "good bye", "good night", "exit"]:
        print("Bot: Bye!")
        break
    print("Bot:", ask_content_bot(user))

"""AUDIO FILES"""

!pip install groq

!wget -O sample_audio.wav https://www2.cs.uic.edu/~i101/SoundFiles/StarWars3.wav

!wget -O sample_audio.wav https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3

!ls

from groq import Groq
from getpass import getpass

api_key = getpass("Enter your Groq API key: ")
client = Groq(api_key=api_key)

filename = "sample_audio.wav"

with open(filename, "rb") as file:
    transcription = client.audio.transcriptions.create(
        file=(filename, file.read()),
        model="whisper-large-v3",
        temperature=0,
        response_format="verbose_json"
    )

print(transcription.text)

!pip install openai-whisper langdetect pydub
!apt-get install ffmpeg

!wget -O sample_speech.wav https://opensource.org/files/lincoln_gettysburg.wav

import whisper
from langdetect import detect, LangDetectException

model = whisper.load_model("small")
result = model.transcribe("sample_speech.wav")
text = result["text"].strip()
print(text)

try:
    print(detect(text))
except LangDetectException:
    print("Language detect failed")

