# -*- coding: utf-8 -*-
"""Copy of Image_segmentation_rgb_hsvf30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bJO1R5bJ2nPKnh9zTjPNFCWtse8NFeZ
"""

import tensorflow as tf
import matplotlib.pyplot as plt

batch_size = 32
img_height = 180
img_width = 180

import tensorflow_datasets as tfds

(ds_train, ds_val), ds_info = tfds.load(
    "tf_flowers",
    split=["train[:80%]", "train[80%:]"],
    with_info=True,
    as_supervised=True
)

def format_image(image, label):
    image = tf.image.resize(image, (img_height, img_width))
    return image, label

train_ds = ds_train.map(format_image).batch(batch_size).prefetch(tf.data.AUTOTUNE)
val_ds = ds_val.map(format_image).batch(batch_size).prefetch(tf.data.AUTOTUNE)

class_names = ds_info.features["label"].names
print("Classes:", class_names)

for image_batch, labels_batch in train_ds:
    print(image_batch.shape)
    print(labels_batch.shape)
    break

num_classes = len(class_names)

model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.legend()
plt.show()

from PIL import Image
from IPython.display import display
import requests
from io import BytesIO

url = "https://picsum.photos/400"
response = requests.get(url)

img = Image.open(BytesIO(response.content))
display(img)

img.save("on.png")

resized_image = img.resize((200,200))
resized_image

rotated_image = img.resize((500,500)).rotate(45)
rotated_image

crop_image = img.crop((10,10,500,500))
crop_image

grayscale = img.convert("L")
grayscale

"""RGB to Gray Scale"""

# Importing Necessary Libraries from skimage
from skimage import data
from skimage.color import rgb2gray

import matplotlib.pyplot as plt

# Setting the plot size
plt.figure(figsize=(15, 15))

# Sample Image of scikit-image package
coffee = data.coffee()

plt.subplot(1, 2, 1)

# Displaying the sample image
plt.imshow(coffee)
plt.title("Original Image")
plt.axis("off")

# Converting RGB image to Monochrome
gray_coffee = rgb2gray(coffee)

plt.subplot(1, 2, 2)

# Displaying the monochrome image
plt.imshow(gray_coffee, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.show()

"""CONVERTING RGB TO HSV"""

# Importing Necessary Libraries
from skimage import data
from skimage.color import rgb2hsv
import matplotlib.pyplot as plt

# Setting the plot size to 15,15
plt.figure(figsize=(15, 15))

# Sample Image of scikit-image package
astronaut = data.astronaut()

plt.subplot(1, 2, 1)

# Displaying the sample image
plt.imshow(astronaut)

# Converting RGB Image to HSV Image
hsv_astronaut = rgb2hsv(astronaut)

plt.subplot(1, 2, 2)

# Displaying the sample image HSV Format
hsv_astronaut_colorbar = plt.imshow(hsv_astronaut)

# Adjusting colorbar to fit the size of the image
plt.colorbar(hsv_astronaut_colorbar, fraction=0.026, pad=0.04)